#!/bin/bash

make clean
make distclean

./configure                         \
  --enable-pythoninterp=yes         \
  --enable-python3interp=yes         \
  --enable-rubyinterp=yes           \
  --enable-multibyte=yes            \
  --enable-luainterp=yes            \
  --enable-mzschemeinterp=yes       \
  --with-modified-by="Joe Fredette" \
  --with-compiledby="$USER"         \
  --enable-gui=no                   \
  --disable-selinux                 \
  --enable-cscope                   \
  --disable-gtktest

RUBY_LIBS="-framework Ruby"

make

